AWSTemplateFormatVersion: '2010-09-09'
Description: Create an ECR placeholder repo

Resources:
  PlaceHolderEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: placeholder
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
                {
                    "rulePriority": 1,
                    "description": "NoMoreThanOneDay",
                    "selection": {
                        "tagStatus": "untagged",
                        "countType": "sinceImagePushed",
                        "countUnit": "days",
                        "countNumber": 1
                    },
                    "action": {
                        "type": "expire"
                    }
                }
            ]
          }
