AWSTemplateFormatVersion: 2010-09-09
Description: Continuous Integration for project

Parameters:
  ProjectName:
    Type: String
    Description: The name of the GitHub repo to create CodeBuild Project
  FargateStackName:
    Type: String
    Description: Fargate stack ID after creating an ECS cluster
  SecurityGroup:
    Type: String
    Description: Security group for CodeBuild
  AwsEnv:
    Type: String
    Description: AWS Environment
    AllowedValues: 
      - nonprod
      - prod

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties: 
      Name: !Ref ProjectName
      Description: !Sub 'Build Project to quality check and deploy ${ProjectName}'
      Artifacts: 
        Type: NO_ARTIFACTS
      BadgeEnabled: true
      Environment: 
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_ENVIRONMENT
            Value: !Ref AwsEnv
          - Name: APP_NAME
            Value: !Ref ProjectName
          - Name: AWS_ACCOUNT_ID
            Value: !Sub '${AWS::AccountId}'
          - Name: DEPLOY_ENV
            Value: ''
      LogsConfig: 
        CloudWatchLogs: 
          Status: ENABLED
      QueuedTimeoutInMinutes: 480
      ServiceRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/CodeBuildServiceRole'
      Source:
        GitCloneDepth: 1
        Location: !Sub 'https://github.platforms.engineering/kpi-automation/${ProjectName}'
        ReportBuildStatus: true
        Type: GITHUB_ENTERPRISE
      TimeoutInMinutes: 60
      VpcConfig: 
        SecurityGroupIds: 
          - !Ref SecurityGroup
        Subnets: 
          - Fn::ImportValue: !Sub ${FargateStackName}-Subnet1
          - Fn::ImportValue: !Sub ${FargateStackName}-Subnet2
        VpcId:
          Fn::ImportValue: !Sub ${FargateStackName}-Vpc